[workspace]
members = ["crates/proto", "crates/publisher", "crates/subscriber", "crates/smoke", "crates/tui", "app/src-tauri"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
zmq-poc-proto = { path = "crates/proto" }
zmq = "0.10"
serde = { version = "1", features = ["derive"] }
bincode = "1"
crossbeam-channel = "0.5"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
